"""Adapters for the V4 sealed-bet claims (prereg_v9), recomputed from the frozen atlas_v3.jsonl.

The cheap, deterministic bet statistics (the v3-new gradient V, the NPI count, the occupancy grid, the
folklore fraction, the rn-stratum Vs) recompute LIVE from the frozen atlas on every `hardmap repro` — a
real re-derivation, not a read-back. The two expensive statistics (the held-out k* estimator and the
10k-resample bootstrap CIs) are read from the committed `atlas_v3_bets_v4.json` in the fast tier and
regenerated by `dev/score_bets_v4.py` in the full tier — the same fast/full split the factors.kstar claim
uses. All V3_SPEC-coded (the 9-rung approximation instrument); B6 is on rn_membership (clarification-03).
"""
from __future__ import annotations

import functools
import json
import sys
from pathlib import Path

import eightfold
from eightfold import crucible
from eightfold.atlas import load_atlas


def _atlas_dir() -> Path:
    return Path(eightfold.__file__).resolve().parent / "results" / "atlas"


def _v3_spec():
    """V3_SPEC lives beside the kernel in eightfold/dev (the Strata precedent: import read-only)."""
    dev = Path(eightfold.__file__).resolve().parent.parent / "dev"
    if str(dev) not in sys.path:
        sys.path.insert(0, str(dev))
    import quarry_v3_spec
    return quarry_v3_spec.V3_SPEC


@functools.lru_cache(maxsize=1)
def _split():
    v3 = load_atlas(_atlas_dir() / "atlas_v3.jsonl")
    kernel_ids = {e.problem_id for e in load_atlas()}
    new = [e for e in v3 if e.problem_id not in kernel_ids]
    return tuple(v3), tuple(new), frozenset(kernel_ids)


def _rows(entries):
    return [{c.charge: c.value for c in e.charges} for e in entries]


@functools.lru_cache(maxsize=1)
def _committed() -> dict:
    return json.loads((_atlas_dir() / "atlas_v3_bets_v4.json").read_text())


# ── B1 — gradient robustness (v3-new both-real approx<->param V, recomputed live) ──────────────────
def gradient_v3new() -> dict:
    v3, new, _ = _split()
    v = crucible._both_real_v(_rows(new), "approximation", "parameterized", _v3_spec())
    return {"v3new_V_corrected": round(float(v), 4)}


# ── B2 — incompressibility (k* on v3-new); fast reads committed, full regenerates ─────────────────
def kstar_v3new_fast() -> dict:
    return {"k_star": _committed()["B2_incompressibility"]["kstar_v3new_9rung"]}


def kstar_v3new_full() -> dict:
    from eightfold import factors
    _, new, _ = _split()
    return {"k_star": factors.factors_verdict(list(new), _v3_spec())["k_star"]["k_hat_1se"]}


# ── B3 — NPI calibration (count of mis-slottable NPI rows, recomputed live) ────────────────────────
def npi_v3new() -> dict:
    _, new, _ = _split()
    n = sum(1 for e in new for c in e.charges if c.charge == "decision" and c.value == "NPI-candidate")
    return {"n_npi": n}


# ── B4 — occupancy (PH×FPT inhabited, forbidden-cell integrity, gap fills; recomputed live) ────────
def occupancy_v3new() -> dict:
    import re
    v3, new, kernel_ids = _split()
    maps = _rows(v3)
    ids = [e.problem_id for e in v3]
    new_flag = [e.problem_id not in kernel_ids for e in v3]

    def inhabited(assign, only_new=False):
        return any(all(m.get(k) == val for k, val in assign.items())
                   for i, m in enumerate(maps) if (not only_new or new_flag[i]))

    gaps = json.loads((_atlas_dir() / "a3_structure.json").read_text())["H3_forbidden_and_gaps"]
    forb_viol = sum(1 for c in gaps["theorem_forbidden"]
                    if inhabited(dict(p.strip().split("=", 1) for p in c["cell"].split("&"))))
    newly = 0
    for c in gaps["gap_list"]:
        a = {}
        for ch in c["pair"].split("|"):
            m = re.search(rf"{re.escape(ch)}=(\S+?)(?:\s|;|$)", c["claim"])
            if m:
                a[ch] = m.group(1)
        if len(a) == 2 and inhabited(a):
            newly += 1
    return {"ph_fpt_inhabited": inhabited({"decision": "PH-complete", "parameterized": "FPT"}),
            "forbidden_violations": forb_viol, "gap_cells_newly_inhabited": newly}


# ── B5 — folklore gap (published-proof fraction of applicable counting cells, recomputed live) ─────
def folklore_v3new() -> dict:
    spec = _v3_spec()
    _, new, _ = _split()
    real = opn = 0
    for e in new:
        for c in e.charges:
            if c.charge != "counting":
                continue
            if c.value in spec.charge_real_values["counting"]:
                real += 1
            elif c.value == "open":
                opn += 1
    return {"published_proof_fraction": round(real / (real + opn), 3) if (real + opn) else None}


# ── B6 — funnel homogeneity on rn_membership (recomputed live) ─────────────────────────────────────
def funnel_rn_v3new() -> dict:
    spec = _v3_spec()
    v3, new, _ = _split()
    prov = {json.loads(l)["problem_id"]: json.loads(l)
            for l in (_atlas_dir() / "atlas_v3_provenance.jsonl").read_text().splitlines() if l.strip()}
    def rn(pid): return (prov.get(pid) or {}).get("rn_membership", "absent")
    present = [e for e in new if rn(e.problem_id) == "present"]
    absent = [e for e in new if rn(e.problem_id) != "present"]
    vp = crucible._both_real_v(_rows(present), "approximation", "parameterized", spec)
    va = crucible._both_real_v(_rows(absent), "approximation", "parameterized", spec)
    return {"V_rn_present": round(float(vp), 4), "V_rn_absent": round(float(va), 4)}
